### ISSUE TITLE
홈 화면 구현

### ISSUE THREAD

**Issue by stellarbg** [ComePetHome/ComePetHome-android#10]
### Todo

- [x] 홈 화면 UI 구현
- [x] 리사이클러뷰 만들기
- [x] 검색 아이콘 클릭시 이동
- [x] 서버로 부터 로그인 안했을 때 데이터 받아오는 기능 구현
- [x] 서버로 부터 로그인 했을 때 데이터 받아오는 기능 구현
