### ISSUE TITLE
홈 화면 상세페이지 화면 구현

### ISSUE THREAD

**Issue by stellarbg** [ComePetHome/ComePetHome-android#18]
### Todo

- [x] 홈 화면 상세페이지 UI 구현
- [x] 지도 구현
- [x] 동영상 연결
- [x] 서버로 부터 데이터 받아오는 기능 구현
- [x] 좋아요, 좋아요 삭제 기능 구현
