### ISSUE TITLE
회원가입 화면 구현

### ISSUE THREAD

**Issue by stellarbg** [ComePetHome/ComePetHome-android#4]
### Todo

- [x] 아아디 입력 하는 화면 UI 구현
- [x] 비밀번호 입력 하는 화면 UI 구현
- [x] 닉네임 입력 하는 화면 UI 구현
- [x] 이름 입력 하는 화면 UI 구현
- [x] 휴대폰 번호 입력 하는 화면 UI 구현
- [x] 회원가입에 성공하면 api 와 연결
- [x] 아이디 중복 확인 하는 기능 및 화면 구현
- [x] 이메일 인증 구현
